import { Inter } from "next/font/google";
import "@/styles/styles.scss";
import Header from "@/app/components/Header";
import Banner from "@/app/components/Banner";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next js",
};

// template: "%s | Codevolution", due to this we can give any thing to any page individually like title, description, etc. for e.g blog | Codevolution
// this meta data is static
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// in this layout we can make footer and header in it
